[tool.poetry]
name = "deeppavlov_test"
version = "0.1.0"
description = ""
authors = ["Anton Gavrilov <anton.gavrilov@raiffeisen.ru>"]

[tool.poetry.dependencies]
python = "^3.7"
deeppavlov = "^0.14.0"
colorama = "^0.4.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
